<?php
$config["map_inner_phpuidt"] = array (
	"qt=s" => array (
		"14" => "市内公交",
		"2" => "城市检索",
		"20" => "驾车",
		"23" => "地址选择",
		"26" => "特殊查询",
		"300" => "打车",
		"48" => "跨城市公交",
		"7" => "城市列表",
		"801" => "驾车",
		"beauty" => "丽人",
		"cater" => "美食",
		"discount" => "优惠",
		"groupon" => "团购",
		"hospital" => "医院",
		"hotel" => "酒店",
		"life" => "生活",
		"scope" => "景点",
		"shopping" => "购物",
		"0" => "未知",
		"104" => "104",
		"11" => "非行业POI检索"
	),
	"qt=bd2" => array (		
		"300" => "打车",
		"beauty" => "丽人",
		"cater" => "美食",
		"discount" => "优惠",
		"groupon" => "团购",
		"hospital" => "医院",
		"hotel" => "酒店",
		"life" => "生活",
		"scope" => "景点",
		"shopping" => "购物",
		"21" => "非行业范围搜索",
		"-1" => "错误",
		"0" => "未知",
		"104" => "104",
	),
	"qt=con" => array(		
		"26" => "特殊检索",
		"7" => "城市列表",
		"beauty" => "丽人",
		"cater" => "美食",
		"hospital" => "医院",
		"hotel" => "酒店",
		"house" => "房产",
		"life" => "生活",
		"scope" => "景点",
		"shopping" => "购物",
		"11" => "非行业POI检索",
		"0" => "未知",
		"104" => "104",
	),
	"qt=ninf" => array(
		"beauty" => "丽人",
		"cater" => "美食",
		"education" => "教育",
		"enterprise" => "企业",
		"hospital" => "医院",
		"hotel" => "酒店",
		"house" => "房产",
		"life" => "生活",
		"scope" => "景点",
		"shopping" => "购物",
		"traffic" => "交通",
		"104" => "非行业详情",
		//"705" => "非行业详情",
	)
);